### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by jiji-hoon96** [seokwon27/riot_api#1]
## 1. localeCompare
https://github.com/seokwon27/riot_api/blob/e730f0a200e310c994dd5e7503522147033edd93/src/app/api/utils/serverApi.ts#L36-L41

```typescript
return champions.sort((a, b) => a.name.localeCompare(b.name)); 

// 위 문법으로 개선할 수 있습니다
```

## 2. startTransition

https://github.com/seokwon27/riot_api/blob/e730f0a200e310c994dd5e7503522147033edd93/src/app/champions/%5Bid%5D/error.tsx#L25-L27

startTransition을 사용한 이유가 있을까요?

## 3. api 변수명

https://github.com/seokwon27/riot_api/blob/e730f0a200e310c994dd5e7503522147033edd93/src/app/champions/page.tsx#L7

const datas = await getChampionsData(); 하나의 컴포넌트에서 여러개의 datalist를 사용하는 경우 문제가 됩니다. championList 등으로 변경하는 것이 좋아보입니다

## 4. 코드 개선
https://github.com/seokwon27/riot_api/blob/e730f0a200e310c994dd5e7503522147033edd93/src/app/champions/%5Bid%5D/page.tsx#L33

- type Props 이 존재합니다.
- 해당 파일의 return 하위 코드가 너무 길어 가독성이 떨어집니다 코드 리팩토링해주세요!

**Comment by seokwon27** [comment]
1. localeCompare 로 수정해보겠습니다
2. 강의에서 에러페이지 실습하며 사용한 함수여서 그대로 사용해봤습니다
3. 변수명 수정하겠습니다
4. Props를 전달받는 컴포넌트를 만들어 분리하는 방식으로 리팩토링 해보면 될까요??
